/*
 * Riz Programming Language
 * riz_runtime.h — Minimal embeddable runtime for AOT-compiled binaries
 *
 * This single-header library is included by C code generated by `riz --aot`.
 * It provides the dynamic value type, arithmetic ops, and print function.
 */

#ifndef RIZ_RUNTIME_H
#define RIZ_RUNTIME_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <math.h>

/* ─── Value Type ──────────────────────────────────────── */
typedef enum { RT_INT, RT_FLOAT, RT_BOOL, RT_STRING, RT_NONE } RizRT;

typedef struct {
    RizRT type;
    union {
        int64_t i;
        double  f;
        bool    b;
        char*   s;
    } v;
} RVal;

/* ─── Constructors ────────────────────────────────────── */
static inline RVal rv_int(int64_t x)       { RVal r; r.type=RT_INT;    r.v.i=x; return r; }
static inline RVal rv_float(double x)      { RVal r; r.type=RT_FLOAT;  r.v.f=x; return r; }
static inline RVal rv_bool(bool x)         { RVal r; r.type=RT_BOOL;   r.v.b=x; return r; }
static inline RVal rv_none(void)           { RVal r; r.type=RT_NONE;   r.v.i=0; return r; }
static inline RVal rv_str(const char* s)   { RVal r; r.type=RT_STRING; r.v.s=strdup(s); return r; }
static inline RVal rv_str_take(char* s)    { RVal r; r.type=RT_STRING; r.v.s=s;         return r; }

/* ─── Numeric conversion ─────────────────────────────── */
static inline double rv_num(RVal a) {
    return a.type == RT_INT ? (double)a.v.i : a.v.f;
}

/* ─── Arithmetic ──────────────────────────────────────── */
static inline RVal rv_add(RVal a, RVal b) {
    if (a.type==RT_INT && b.type==RT_INT) return rv_int(a.v.i + b.v.i);
    if (a.type==RT_STRING && b.type==RT_STRING) {
        size_t la=strlen(a.v.s), lb=strlen(b.v.s);
        char* c=(char*)malloc(la+lb+1); memcpy(c,a.v.s,la); memcpy(c+la,b.v.s,lb+1);
        return rv_str_take(c);
    }
    return rv_float(rv_num(a) + rv_num(b));
}
static inline RVal rv_sub(RVal a, RVal b) {
    if (a.type==RT_INT && b.type==RT_INT) return rv_int(a.v.i - b.v.i);
    return rv_float(rv_num(a) - rv_num(b));
}
static inline RVal rv_mul(RVal a, RVal b) {
    if (a.type==RT_INT && b.type==RT_INT) return rv_int(a.v.i * b.v.i);
    return rv_float(rv_num(a) * rv_num(b));
}
static inline RVal rv_div(RVal a, RVal b) {
    return rv_float(rv_num(a) / rv_num(b));
}
static inline RVal rv_mod(RVal a, RVal b) {
    if (a.type==RT_INT && b.type==RT_INT) return rv_int(a.v.i % b.v.i);
    return rv_float(fmod(rv_num(a), rv_num(b)));
}
static inline RVal rv_idiv(RVal a, RVal b) {
    if (a.type==RT_INT && b.type==RT_INT) return rv_int(a.v.i / b.v.i);
    return rv_int((int64_t)floor(rv_num(a) / rv_num(b)));
}
static inline RVal rv_pow(RVal a, RVal b) {
    double r = pow(rv_num(a), rv_num(b));
    if (a.type==RT_INT && b.type==RT_INT && b.v.i >= 0) return rv_int((int64_t)r);
    return rv_float(r);
}
static inline RVal rv_neg(RVal a) {
    if (a.type==RT_INT) return rv_int(-a.v.i);
    return rv_float(-a.v.f);
}

/* ─── Comparison ──────────────────────────────────────── */
static inline bool rv_eq(RVal a, RVal b) {
    if (a.type != b.type) return false;
    switch (a.type) {
        case RT_INT:    return a.v.i == b.v.i;
        case RT_FLOAT:  return a.v.f == b.v.f;
        case RT_BOOL:   return a.v.b == b.v.b;
        case RT_STRING: return strcmp(a.v.s, b.v.s) == 0;
        case RT_NONE:   return true;
    }
    return false;
}
static inline bool rv_truthy(RVal a) {
    switch (a.type) {
        case RT_INT:   return a.v.i != 0;
        case RT_FLOAT: return a.v.f != 0.0;
        case RT_BOOL:  return a.v.b;
        case RT_STRING: return a.v.s[0] != '\0';
        case RT_NONE:  return false;
    }
    return false;
}

/* ─── Print ───────────────────────────────────────────── */
static inline void rv_print_val(RVal v) {
    switch (v.type) {
        case RT_INT:    printf("%lld", (long long)v.v.i); break;
        case RT_FLOAT: {
            double d = v.v.f;
            if (d == (int64_t)d && fabs(d) < 1e15) printf("%.1f", d);
            else printf("%g", d);
            break;
        }
        case RT_BOOL:   printf("%s", v.v.b ? "true" : "false"); break;
        case RT_STRING: printf("%s", v.v.s); break;
        case RT_NONE:   printf("none"); break;
    }
}

static inline void rv_print(int n, ...) {
    __builtin_va_list ap;
    __builtin_va_start(ap, n);
    for (int i = 0; i < n; i++) {
        if (i > 0) printf(" ");
        rv_print_val(__builtin_va_arg(ap, RVal));
    }
    printf("\n");
    __builtin_va_end(ap);
}

#endif /* RIZ_RUNTIME_H */
