/*
 * Riz — low-friction environment: doctor, setup, shell activation snippets.
 */

#include "riz_env.h"
#include "common.h"
#include "pkg.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <direct.h>
#include <io.h>
#define MKDIR_E(d) _mkdir(d)
#else
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <limits.h>
#define MKDIR_E(d) mkdir((d), 0755)
#endif

#if defined(__APPLE__)
#include <mach-o/dyld.h>
#endif

static void ensure_dir_e(const char* path) { MKDIR_E(path); }

static bool file_exists_p(const char* p) {
    FILE* f = fopen(p, "rb");
    if (f) {
        fclose(f);
        return true;
    }
    return false;
}

/* Fill out with directory containing this executable (no trailing slash). */
static bool riz_binary_dir(char* out, size_t cap, const char* argv0) {
    char buf[4096];
    buf[0] = '\0';

#ifdef _WIN32
    DWORD n = GetModuleFileNameA(NULL, buf, (DWORD)sizeof(buf) - 1);
    if (n == 0 || n >= sizeof(buf) - 1) {
        if (argv0 && argv0[0])
            strncpy(buf, argv0, sizeof(buf) - 1);
    }
#elif defined(__linux__)
    ssize_t r = readlink("/proc/self/exe", buf, sizeof(buf) - 2);
    if (r > 0)
        buf[r] = '\0';
#elif defined(__APPLE__)
    uint32_t sz = (uint32_t)sizeof(buf);
    if (_NSGetExecutablePath(buf, &sz) != 0)
        buf[0] = '\0';
#else
    (void)argv0;
#endif
    if (!buf[0] && argv0 && argv0[0])
        strncpy(buf, argv0, sizeof(buf) - 1);

    if (!buf[0])
        return false;

#if defined(__APPLE__)
    {
        char resolved[4096];
        if (realpath(buf, resolved))
            strncpy(buf, resolved, sizeof(buf) - 1);
        buf[sizeof(buf) - 1] = '\0';
    }
#endif

    /* Strip filename */
    char* slash = strrchr(buf, '/');
#ifdef _WIN32
    char* bs = strrchr(buf, '\\');
    if (bs > slash)
        slash = bs;
#endif
    if (!slash)
        return false;
    *slash = '\0';
    strncpy(out, buf, cap - 1);
    out[cap - 1] = '\0';
    return out[0] != '\0';
}

static void cwd_basename(char* out, size_t cap) {
#ifdef _WIN32
    char cwd[1024];
    if (_getcwd(cwd, sizeof(cwd) - 1) == NULL) {
        strncpy(out, "myriz", cap - 1);
        out[cap - 1] = '\0';
        return;
    }
    char* a = strrchr(cwd, '\\');
    char* b = strrchr(cwd, '/');
    char* s = (a > b) ? a : b;
#else
    char cwd[1024];
    if (!getcwd(cwd, sizeof(cwd))) {
        strncpy(out, "myriz", cap - 1);
        out[cap - 1] = '\0';
        return;
    }
    char* s = strrchr(cwd, '/');
#endif
    strncpy(out, s ? (s + 1) : cwd, cap - 1);
    out[cap - 1] = '\0';
    /* Sanitize empty / odd names */
    if (!out[0] || strcmp(out, ".") == 0)
        strncpy(out, "myriz", cap - 1);
}

static bool find_riz_sdk_root(char* out, size_t cap) {
#ifdef _WIN32
    char cwd[1024];
    if (_getcwd(cwd, sizeof(cwd) - 1) == NULL)
        return false;
#else
    char cwd[1024];
    if (!getcwd(cwd, sizeof(cwd)))
        return false;
#endif
    char walk[1024];
    strncpy(walk, cwd, sizeof(walk) - 1);
    walk[sizeof(walk) - 1] = '\0';

    for (int depth = 0; depth < 96; depth++) {
        char test[1200];
        snprintf(test, sizeof(test), "%s/src/aot_runtime.c", walk);
        if (file_exists_p(test)) {
            strncpy(out, walk, cap - 1);
            out[cap - 1] = '\0';
            return true;
        }
#ifdef _WIN32
        char* a = strrchr(walk, '\\');
        char* b = strrchr(walk, '/');
        char* slash = (a > b) ? a : b;
#else
        char* slash = strrchr(walk, '/');
#endif
        if (!slash || slash == walk)
            break;
        *slash = '\0';
#ifdef _WIN32
        if (strlen(walk) == 2 && walk[1] == ':')
            break;
#endif
    }
    return false;
}

static int sh_quote(const char* in, char* out, size_t cap) {
    size_t j = 0;
    out[j++] = '"';
    for (const unsigned char* p = (const unsigned char*)in; *p && j + 2 < cap; p++) {
        if (*p == '"' || *p == '\\' || *p == '$' || *p == '`') {
            if (j + 3 >= cap)
                return -1;
            out[j++] = '\\';
        }
        out[j++] = (char)*p;
    }
    if (j + 1 >= cap)
        return -1;
    out[j++] = '"';
    out[j] = '\0';
    return 0;
}

static int write_activate_scripts(const char* bindir, const char* sdk_root) {
    ensure_dir_e(".riz");

    char qbin[5120];
    if (sh_quote(bindir, qbin, sizeof(qbin)) != 0)
        return 1;

    FILE* sh = fopen(".riz/activate.sh", "wb");
    if (!sh)
        return 1;
    fprintf(sh, "# Generated by `riz env setup` — POSIX shell\n");
    fprintf(sh, "export PATH=%s:\"$PATH\"\n", qbin);
    if (sdk_root && sdk_root[0]) {
        char qs[5120];
        if (sh_quote(sdk_root, qs, sizeof(qs)) == 0)
            fprintf(sh, "export RIZ_SOURCE_ROOT=%s\n", qs);
    }
    fprintf(sh, "# Usage: . ./.riz/activate.sh   (or: source ./.riz/activate.sh)\n");
    fclose(sh);

    FILE* ps = fopen(".riz/activate.ps1", "wb");
    if (!ps)
        return 1;
    fprintf(ps, "# Generated by `riz env setup` — PowerShell\n");
    fprintf(ps, "$RizBin = @'\n%s\n'@\n", bindir);
    fprintf(ps, "if ($env:Path -notlike \"*$RizBin*\") { $env:Path = \"$RizBin;$env:Path\" }\n");
    if (sdk_root && sdk_root[0])
        fprintf(ps, "$env:RIZ_SOURCE_ROOT = @'\n%s\n'@\n", sdk_root);
    fprintf(ps, "# Usage: . .\\.riz\\activate.ps1\n");
    fclose(ps);

    return 0;
}

static void gitignore_riz_cache_once(void) {
    const char* needle = ".riz/cache";
    FILE* r = fopen(".gitignore", "rb");
    if (!r)
        return;
    fseek(r, 0, SEEK_END);
    long sz = ftell(r);
    if (sz < 0 || sz > 1024 * 1024) {
        fclose(r);
        return;
    }
    rewind(r);
    char* buf = (char*)malloc((size_t)sz + 1);
    if (!buf) {
        fclose(r);
        return;
    }
    size_t n = fread(buf, 1, (size_t)sz, r);
    fclose(r);
    buf[n] = '\0';
    if (strstr(buf, needle)) {
        free(buf);
        return;
    }
    free(buf);

    FILE* a = fopen(".gitignore", "ab");
    if (!a)
        return;
    fprintf(a, "\n# Riz package cache (generated)\n.riz/cache\n");
    fclose(a);
}

static int cmd_doctor(void) {
    printf(COL_BOLD "Riz environment" COL_RESET " (v%s)\n\n", RIZ_VERSION);

    int issues = 0;

#ifdef _WIN32
    if (system("gcc --version > NUL 2>&1") == 0)
        printf("  [" COL_GREEN "ok" COL_RESET "] gcc found (AOT recommended)\n");
    else {
        printf("  [" COL_YELLOW "warn" COL_RESET "] gcc not on PATH — AOT falls back to vendor\\tcc\\tcc.exe\n");
        issues++;
    }
#else
    if (system("gcc --version > /dev/null 2>&1") == 0)
        printf("  [" COL_GREEN "ok" COL_RESET "] gcc found\n");
    else if (system("clang --version > /dev/null 2>&1") == 0)
        printf("  [" COL_GREEN "ok" COL_RESET "] clang found\n");
    else {
        printf("  [" COL_RED "fail" COL_RESET "] no gcc/clang — install a C11 toolchain for AOT\n");
        issues++;
    }
#endif

#ifdef _WIN32
    if (system("git --version > NUL 2>&1") == 0)
#else
    if (system("git --version > /dev/null 2>&1") == 0)
#endif
        printf("  [" COL_GREEN "ok" COL_RESET "] git (for git+ dependencies)\n");
    else
        printf("  [" COL_YELLOW "warn" COL_RESET "] git missing — git-based `riz pkg` deps will fail\n");

#ifdef _WIN32
    if (system("curl --version > NUL 2>&1") == 0)
        printf("  [" COL_GREEN "ok" COL_RESET "] curl (package index download)\n");
    else {
        printf("  [" COL_YELLOW "warn" COL_RESET "] curl missing — pkg may use PowerShell for HTTP\n");
        issues++;
    }
#else
    if (system("curl --version > /dev/null 2>&1") == 0)
        printf("  [" COL_GREEN "ok" COL_RESET "] curl\n");
    else if (system("wget --version > /dev/null 2>&1") == 0)
        printf("  [" COL_GREEN "ok" COL_RESET "] wget\n");
    else
        printf("  [" COL_YELLOW "warn" COL_RESET "] neither curl nor wget — remote package index fetch may fail\n");
#endif

#ifdef _WIN32
    if (file_exists_p("vendor\\tcc\\tcc.exe"))
#else
    if (file_exists_p("vendor/tcc/tcc") || file_exists_p("vendor/tcc/tcc.exe"))
#endif
        printf("  [" COL_GREEN "ok" COL_RESET "] bundled TinyCC under vendor/tcc\n");
    else
        printf("  [" COL_DIM "info" COL_RESET "] no vendor/tcc (optional Windows AOT fallback)\n");

    char sdk[1024];
    if (find_riz_sdk_root(sdk, sizeof(sdk)))
        printf("  [" COL_GREEN "ok" COL_RESET "] Riz SDK checkout detected: %s\n", sdk);
    else
        printf("  [" COL_DIM "info" COL_RESET "] not inside a Riz repo (no src/aot_runtime.c above cwd)\n");

    const char* py = getenv("RIZ_SKIP_PYTHON_CHECK");
    if (!py || !py[0]) {
#ifdef _WIN32
        if (system("python --version > NUL 2>&1") == 0 || system("py -3 --version > NUL 2>&1") == 0)
#else
        if (system("python3 --version > /dev/null 2>&1") == 0 || system("python --version > /dev/null 2>&1") == 0)
#endif
            printf("  [" COL_GREEN "ok" COL_RESET "] Python on PATH (plugin_python / tooling)\n");
        else
            printf("  [" COL_DIM "info" COL_RESET "] Python not detected (skip if you do not use plugin_python)\n");
    }

    printf("\n");
    if (issues == 0)
        printf(COL_GREEN "No blocking issues detected." COL_RESET "\n");
    else
        printf(COL_YELLOW "Some optional tools missing — see above." COL_RESET "\n");
    printf("Quick fix: " COL_CYAN "riz env setup" COL_RESET " in your project root.\n");
    return 0;
}

static int run_pkg_argv(const char* a0, const char* a1, const char* a2) {
    char b0[32], b1[256], b2[256];
    strncpy(b0, a0, sizeof(b0) - 1);
    b0[sizeof(b0) - 1] = '\0';
    char* av[4];
    int ac = 1;
    av[0] = b0;
    if (a1) {
        strncpy(b1, a1, sizeof(b1) - 1);
        b1[sizeof(b1) - 1] = '\0';
        av[1] = b1;
        ac = 2;
    }
    if (a2) {
        strncpy(b2, a2, sizeof(b2) - 1);
        b2[sizeof(b2) - 1] = '\0';
        av[2] = b2;
        ac = 3;
    }
    return riz_pkg_main(ac, av);
}

static int cmd_init(int argc, char** argv) {
    if (argc >= 1)
        return run_pkg_argv("init", argv[0], NULL);
    char name[256];
    cwd_basename(name, sizeof(name));
    return run_pkg_argv("init", name, NULL);
}

static int cmd_setup(int argc, char** argv, const char* program_path) {
    char bindir[4096];
    if (!riz_binary_dir(bindir, sizeof(bindir), program_path)) {
        fprintf(stderr,
                "env: could not resolve path to `riz` binary; pass full path to riz.exe, or run from a shell "
                "where argv[0] is absolute.\n");
        strncpy(bindir, ".", sizeof(bindir) - 1);
        bindir[sizeof(bindir) - 1] = '\0';
    }

#ifdef _WIN32
    bool have_json = (_access("riz.json", 0) == 0);
#else
    bool have_json = (access("riz.json", F_OK) == 0);
#endif
    if (!have_json) {
        char name[256];
        if (argc >= 1 && argv[0] && argv[0][0])
            strncpy(name, argv[0], sizeof(name) - 1);
        else
            cwd_basename(name, sizeof(name));
        name[sizeof(name) - 1] = '\0';
        printf(COL_DIM "[env] creating project (riz.json)…" COL_RESET "\n");
        if (run_pkg_argv("init", name, NULL) != 0)
            return 1;
    }

    ensure_dir_e("vendor");
    ensure_dir_e(".riz");

    int nd = riz_pkg_merged_dep_count();
    if (nd > 0) {
        printf(COL_DIM "[env] installing %d dependenc%s…" COL_RESET "\n", nd, nd == 1 ? "y" : "ies");
        if (run_pkg_argv("install", NULL, NULL) != 0)
            return 1;
    } else {
        printf(COL_DIM "[env] no dependencies yet — edit riz.deps or use `riz pkg add`" COL_RESET "\n");
    }

    char sdk[1024];
    sdk[0] = '\0';
    if (find_riz_sdk_root(sdk, sizeof(sdk)))
        printf(COL_DIM "[env] RIZ_SOURCE_ROOT=%s (for AOT from this tree)" COL_RESET "\n", sdk);

    if (write_activate_scripts(bindir, sdk[0] ? sdk : NULL) != 0) {
        fprintf(stderr, "env: could not write .riz/activate.{sh,ps1}\n");
        return 1;
    }

    gitignore_riz_cache_once();

    printf("\n" COL_GREEN COL_BOLD "env: setup complete." COL_RESET "\n");
    printf("  POSIX:  " COL_CYAN ". ./.riz/activate.sh" COL_RESET "\n");
    printf("  PowerShell:  " COL_CYAN ". .\\.riz\\activate.ps1" COL_RESET "\n");
    printf("  One-liner (bash):  " COL_CYAN "eval \"$(riz env shell bash)\"" COL_RESET "\n");
    return 0;
}

static int cmd_shell(int argc, char** argv, const char* program_path) {
    char bindir[4096];
    if (!riz_binary_dir(bindir, sizeof(bindir), program_path)) {
        fprintf(stderr, "env: could not resolve riz binary path\n");
        return 1;
    }
    const char* sh = "bash";
    if (argc >= 1 && argv[0] && argv[0][0])
        sh = argv[0];

    if (strcmp(sh, "bash") == 0 || strcmp(sh, "zsh") == 0 || strcmp(sh, "sh") == 0) {
        char q[5120];
        if (sh_quote(bindir, q, sizeof(q)) != 0)
            return 1;
        printf("export PATH=%s:\"$PATH\"\n", q);
        return 0;
    }
    if (strcmp(sh, "powershell") == 0 || strcmp(sh, "pwsh") == 0) {
        printf("$env:Path = @'\n%s\n'@ + ';' + $env:Path\n", bindir);
        return 0;
    }
    if (strcmp(sh, "fish") == 0) {
        char q[5120];
        if (sh_quote(bindir, q, sizeof(q)) != 0)
            return 1;
        printf("set -gx PATH %s $PATH\n", q);
        return 0;
    }
    fprintf(stderr, "env: unknown shell '%s' (try: bash, powershell, fish)\n", sh);
    return 1;
}

static void print_env_usage(void) {
    fprintf(stderr,
            "Usage:\n"
            "  riz env doctor              Check toolchain (gcc, git, curl, tcc, sdk)\n"
            "  riz env setup [name]        Init project if needed, vendor/, pkg install, activate scripts\n"
            "  riz env init [name]         Same as `riz pkg init` (shorthand)\n"
            "  riz env shell [bash|powershell|fish]   Print PATH snippet for eval\n\n"
            "Typical zero-config flow in a new directory:\n"
            "  riz env setup && . ./.riz/activate.sh    # POSIX\n"
            "  riz env setup; . .\\.riz\\activate.ps1    # Windows PowerShell\n");
}

int riz_env_main(int argc, char** argv, const char* program_path) {
    if (argc < 1 || strcmp(argv[0], "-h") == 0 || strcmp(argv[0], "--help") == 0 || strcmp(argv[0], "help") == 0) {
        print_env_usage();
        return argc < 1 ? 1 : 0;
    }
    if (strcmp(argv[0], "doctor") == 0)
        return cmd_doctor();
    if (strcmp(argv[0], "setup") == 0)
        return cmd_setup(argc - 1, argv + 1, program_path);
    if (strcmp(argv[0], "init") == 0)
        return cmd_init(argc - 1, argv + 1);
    if (strcmp(argv[0], "shell") == 0)
        return cmd_shell(argc - 1, argv + 1, program_path);

    fprintf(stderr, "env: unknown subcommand '%s'\n", argv[0]);
    print_env_usage();
    return 1;
}
